# Colección de ejercicios de Numpy

## 1 - Importa el paquete con el nombre "np".

`pista: import … as …`

In [2]:
import numpy as np

## 2 - Imprime la versión instalada.

`pista: np.__version__, np.show_config`

In [4]:
print(np.__version__)
print(np.show_config)

1.26.4
<function show at 0x000002A019329B20>


## 3 - Crea un vector de nulos de tamaño 10.

`pista: np.zeros`

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4 - Encontrar el tamaño en memoria de un array.

`pista: size, itemsize`

In [8]:
array = np.random.rand(10,10)

tamaño_memoria = array.size*array.itemsize
print(tamaño_memoria)

800


## 5 - Cree un vector nulo de tamaño 10 pero el quinto valor tiene de valor 1.

`pista: array[...]`

In [10]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 6 - Cree un vector con valores que van de 10 a 49.

`pista: arange`


In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 7 - Invierta un vector (el primer elemento se convierte en el último).

`pista: array[::-1]`

In [15]:
vector = np.arange(0,10)
print(vector[::-1])

[9 8 7 6 5 4 3 2 1 0]


## 8 Cree una matriz de 3x3 con valores que van de 0 a 8.

`pista: reshape`

In [17]:
array_1d = np.arange(9)
array_1d.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 9 - Encuentre los índices de elementos distintos de cero de `[7,5,0,0,2,1]`.

`pista: np.nonzero`

In [21]:
array = np.array([7, 5, 0, 0, 2, 1])
indices_distintos_de_cero = np.nonzero(array)
array[indices_distintos_de_cero]

array([7, 5, 2, 1])

## 10 - Crear una matriz de identidad de 3x3.

`pista: np.eye`


In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 11 - Crear una matriz de 3x3x3 con valores aleatorios.

`pista: np.random.randn`


In [46]:
np.random.randn(3,3,3)

array([[[ 1.06746419, -1.19276757, -0.8108907 ],
        [-0.12538503,  0.71095113, -1.32130305],
        [-0.62077279, -0.1833992 , -1.87129868]],

       [[ 0.16990221,  0.56017463,  0.34819629],
        [-1.14476209,  0.81101458,  0.6126597 ],
        [-0.14834045,  0.14728221,  0.52741611]],

       [[-0.54546875,  0.06326525,  0.58735747],
        [-2.42296091,  2.06729092,  1.39972804],
        [ 0.56875119, -0.99766637, -0.38751739]]])

## 12 - Cree una matriz de 10x10 con valores aleatorios y encuentre el mínimo y el máximo.

`pista: min, max`

In [51]:
matriz = np.random.randn(10,10)
print(matriz)
print(np.max(matriz))
print(np.min(matriz))

[[ 6.34065729e-01  1.63604688e+00  1.55450869e+00  7.90014483e-01
   5.66086445e-01  1.92625886e-01  1.27380137e+00  2.08733028e+00
  -4.26990646e-01 -8.26801626e-01]
 [ 1.04701362e-01 -1.46790217e+00 -8.56823374e-01  1.02179154e+00
   4.24441395e-01 -4.49615341e-01 -1.38761148e-01  5.78373018e-01
  -1.23859961e-01  1.10108222e-01]
 [ 4.99951081e-01  1.37777846e+00  1.18113246e+00  2.97206269e-01
   6.18287353e-01  6.66514694e-02  5.18154060e-01 -1.18679968e+00
   1.41810107e+00  2.40300030e-01]
 [ 7.45581909e-01  7.48900296e-01 -1.06204740e-01  4.18137858e-02
  -4.10696114e-01  5.24915591e-01 -6.15937563e-02 -4.15177290e-01
  -1.11157335e+00 -1.15994032e+00]
 [ 6.49819463e-01  3.15866245e-01 -2.41954850e-01  1.92908009e-01
  -3.96147534e-01  7.22141101e-01  6.29413981e-01  5.56958335e-01
   5.48226273e-02 -7.71132358e-01]
 [ 2.20886581e+00 -8.69268622e-02  2.67203859e-03 -5.95230732e-03
  -1.07631155e+00  1.16421475e+00 -8.53198668e-01  3.41588533e-01
  -6.79869158e-03 -8.17957709e-01

## 13 - Cree un vector aleatorio de tamaño 50 y encuentre el valor medio.

`pista: mean`

In [53]:
vector = np.random.rand(50)
np.mean(vector)

0.5203385600076185

## 14 - Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.

`pista: np.diag`

In [58]:
np.zeros((6,6))
valores_debajo_diagonal = [1, 2, 3, 4, 5]
matriz = np.diag(valores_debajo_diagonal, k=-1)
print(matriz)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


## 15 - Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?

`pista: np.unravel_index`

In [103]:
forma = (4, 5, 6) #4 matrices 5 filas 6 columnas


# Número total de elementos antes del elemento número 57
indice_57 = 57 - 1  # Restamos 1 porque los índices comienzan desde 0

# Calcular el índice (x, y, z)
indice_xyz = np.unravel_index(indice_57, forma)

# Imprimir el índice (x, y, z)
print("El índice del elemento número 57 es:", indice_xyz)
print(np.random.randint(0,10,(4,5,6)))


El índice del elemento número 57 es: (1, 4, 2)
[[[7 2 7 4 9 6]
  [5 5 8 6 4 4]
  [3 3 3 2 3 8]
  [3 4 3 3 2 8]
  [7 6 8 4 8 1]]

 [[6 4 1 4 0 5]
  [9 9 3 7 1 8]
  [4 8 3 0 1 9]
  [6 1 6 4 9 9]
  [4 9 8 2 3 9]]

 [[6 8 4 2 2 8]
  [1 9 3 8 0 2]
  [9 2 9 5 9 9]
  [4 0 5 3 5 3]
  [4 4 3 9 1 4]]

 [[5 3 8 2 7 8]
  [0 9 2 9 7 8]
  [9 7 9 1 8 7]
  [3 1 9 2 6 4]
  [8 2 8 0 2 4]]]


## 16 - Normalice una matriz aleatoria de 10x10.

`pista: (x - mean) / std`

In [60]:
matriz = np.random.randn(10,10)
media = np.mean(matriz)
std = np.std(matriz)
matriz_normalizada = (matriz-media) / std
print(matriz_normalizada)


[[ 0.8492903  -1.28966126 -0.73114505  1.22562581 -1.83324751  0.40416573
  -0.18753674 -1.00795454  0.14909859 -0.41547111]
 [-2.08913101 -1.25036671  1.0812046  -0.64657104  1.62314033 -0.44309964
  -0.54361318  1.25180036 -0.41738271 -2.10114525]
 [-1.22364586 -0.97549066  0.15584491  0.68809812  0.03304797 -1.09669804
   1.48209127 -1.42952629 -1.04743611 -0.65554871]
 [ 0.13581285  1.8503108   0.72868118  0.27111565 -0.0934772  -0.67707327
  -0.36956977 -1.01056     1.65816223 -1.40916047]
 [ 1.02819771  0.11916991 -0.61438873 -0.75985145 -1.12860374  1.96128313
   0.70312502 -0.25816735  0.69982668 -1.7015586 ]
 [-0.23601544  0.81280428 -2.56596145  0.94468146  1.9664984   0.48798157
   0.65655198 -0.22741925  0.58158111  1.80989203]
 [-0.18373173  0.16548378  1.02636971  1.12371836 -0.68077763  1.20820129
   0.51275947 -0.76211086 -0.19572793  1.05423003]
 [-1.38580556  0.25192959  0.94210331  0.06597435  0.57024662  0.39396406
  -0.17596525 -0.22189056  2.01041883  0.34491552]


## 17 - Multiplique una matriz de 3x2 por una matriz de 2x5.

In [105]:
matriz1 = np.random.rand(3, 2)
matriz2 = np.random.rand(2, 5)

resultado = np.dot(matriz1, matriz2)
print(resultado)

[[0.34959918 0.61970567 0.43238345 0.55205522 0.15005286]
 [0.53816939 0.78202048 0.51622136 0.76772931 0.32680265]
 [0.21088081 0.24144188 0.14581702 0.26980242 0.16427167]]


[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


## 18 - ¿Cómo encuentra valores comunes entre dos matrices?

`pista: np.intersect1d`


In [72]:
matriz1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matriz2 = np.array([[2, 4, 6],
                     [8, 10, 12],
                     [14, 16, 18]])
np.intersect1d(matriz1,matriz2)

array([2, 4, 6, 8])

## 19 - ¿Cómo obtener las fechas de ayer, hoy y mañana?

`pista: np.datetime64, np.timedelta64`


In [106]:
import numpy as np

# Obtener la fecha de hoy
fecha_hoy = np.datetime64('today', 'D')

# Obtener la fecha de ayer restando un día a la fecha de hoy
fecha_ayer = fecha_hoy - np.timedelta64(1, 'D')

# Obtener la fecha de mañana sumando un día a la fecha de hoy
fecha_maniana = fecha_hoy + np.timedelta64(1, 'D')

# Imprimir las fechas
print(f"Hoy es {fecha_hoy}, ayer fue {fecha_ayer} y mañana será {fecha_maniana}")

Fecha de ayer: 2024-05-26
Fecha de hoy: 2024-05-27
Fecha de mañana: 2024-05-28
Hoy es 2024-05-27, ayer fue 2024-05-26 y mañana será 2024-05-28


## 20 - ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?

`pista: np.arange(dtype=datetime64['D'])`

In [75]:
np.arange('2020-09','2020-10', dtype='datetime64[D]')

array(['2020-09-01', '2020-09-02', '2020-09-03', '2020-09-04',
       '2020-09-05', '2020-09-06', '2020-09-07', '2020-09-08',
       '2020-09-09', '2020-09-10', '2020-09-11', '2020-09-12',
       '2020-09-13', '2020-09-14', '2020-09-15', '2020-09-16',
       '2020-09-17', '2020-09-18', '2020-09-19', '2020-09-20',
       '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24',
       '2020-09-25', '2020-09-26', '2020-09-27', '2020-09-28',
       '2020-09-29', '2020-09-30'], dtype='datetime64[D]')

## 21 - Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.

`pista: %, np.floor, astype, np.trunc`

In [82]:
matriz_aleatoria = np.random.rand(5, 5) * 100
# Método 1: Usando el operador módulo (%)
parte_entera_modulo = matriz_aleatoria % 1

# Método 2: Usando la función np.floor()
parte_entera_floor = np.floor(matriz_aleatoria)

# Método 3: Usando el método astype(int)
parte_entera_astype = matriz_aleatoria.astype(int)

# Método 4: Usando la función np.trunc()
parte_entera_trunc = np.trunc(matriz_aleatoria)
print(matriz_aleatoria)
# Imprimir los resultados
print("Método 1 - Usando el operador módulo (%):\n", parte_entera_modulo)
print("\nMétodo 2 - Usando la función np.floor():\n", parte_entera_floor)
print("\nMétodo 3 - Usando el método astype(int):\n", parte_entera_astype)
print("\nMétodo 4 - Usando la función np.trunc():\n", parte_entera_trunc)


[[22.66493394 80.40974226 73.16688625 60.27057836 43.59898614]
 [37.31996602 99.15031502 66.63156316 82.7299785  23.23952708]
 [78.59532704 30.01904054  6.6826479  90.24531547 54.56683767]
 [ 2.90700729 85.04104691 77.9938173  68.48740192  6.29678672]
 [34.33801256 17.83789082 73.38953432 50.14523373 69.92075241]]
Método 1 - Usando el operador módulo (%):
 [[0.66493394 0.40974226 0.16688625 0.27057836 0.59898614]
 [0.31996602 0.15031502 0.63156316 0.7299785  0.23952708]
 [0.59532704 0.01904054 0.6826479  0.24531547 0.56683767]
 [0.90700729 0.04104691 0.9938173  0.48740192 0.29678672]
 [0.33801256 0.83789082 0.38953432 0.14523373 0.92075241]]

Método 2 - Usando la función np.floor():
 [[22. 80. 73. 60. 43.]
 [37. 99. 66. 82. 23.]
 [78. 30.  6. 90. 54.]
 [ 2. 85. 77. 68.  6.]
 [34. 17. 73. 50. 69.]]

Método 3 - Usando el método astype(int):
 [[22 80 73 60 43]
 [37 99 66 82 23]
 [78 30  6 90 54]
 [ 2 85 77 68  6]
 [34 17 73 50 69]]

Método 4 - Usando la función np.trunc():
 [[22. 80. 73. 

## 22 - Cree una matriz de 10x10 con valores de fila que van de 0 a 9.

`pista: np.arange`

In [100]:
np.arange(10).reshape(1,10) + np.zeros((10,10))

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

## 23 - Cree un vector de tamaño 5 con valores que van de 0 a 1, ambos excluidos.

`pista: np.linspace`

In [12]:
np.linspace(0,1,7)[1:-1]

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

## 24 - Cree un vector aleatorio de tamaño 25 y ordénelo.

`pista: sort`

In [14]:
vector_aleatorio = np.random.rand(25)
np.sort(vector_aleatorio)

array([0.02992261, 0.03282699, 0.04919101, 0.07421669, 0.08241858,
       0.11563545, 0.15090495, 0.19438853, 0.21975529, 0.22899301,
       0.2376682 , 0.32779863, 0.35538207, 0.38595488, 0.39691401,
       0.44555029, 0.48788314, 0.51519352, 0.57324254, 0.58101791,
       0.60166895, 0.65175815, 0.66354485, 0.72833623, 0.83709297])

## 25 - Sume un vector usando `np.add.reduce`.

In [15]:
vector = np.random.rand(10)
suma_vector = np.add.reduce(vector)
print(vector)
print(suma_vector)

[0.36883247 0.47265781 0.56282487 0.10701165 0.59834174 0.08284359
 0.98373949 0.49291256 0.80882757 0.63699255]
5.114984295582998


## 26 - Considere dos matrices aleatorias A y B, verifique si son iguales.

`pista: np.allclose, np.array_equal`

In [24]:
matriza = np.random.rand(3, 3)
matrizb = np.random.rand(3, 3)
print(np.allclose(matriza,matrizb))
print(np.array_equal(matriza,matrizb))



False
False


## 27 - Cree un vector aleatorio de tamaño 25 y reemplace el valor máximo por 0.

`pista: argmax`


In [47]:
vector_aleatorio = np.random.rand(25)
indice_max = np.argmax(vector_aleatorio)
vector_aleatorio[indice_max] = 0
print(vector_aleatorio)

[0.21208491 0.52777121 0.39309076 0.         0.07603947 0.02578151
 0.57821925 0.43321143 0.75595408 0.46609802 0.08300976 0.67784271
 0.16276079 0.09047216 0.14497214 0.75117217 0.58702857 0.87764313
 0.33663521 0.02250462 0.40161394 0.70508308 0.08797007 0.68543667
 0.95121193]


## 28 - ¿Cómo imprimir todos los valores de una matriz?

`pista: np.set_printoptions`

In [56]:
matriz = np.zeros((10,10))
np.set_printoptions(threshold=np.inf)
print(matriz)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 29 - ¿Cómo encontrar el valor más cercano, a un escalar dado, en un vector?

`pista: argmin`


In [61]:
vector = np.arange(100)

escalar = 71.07785907592171

indice_mas_cercano = np.abs(vector - escalar).argmin()

valor_mas_cercano = vector[indice_mas_cercano]
print(vector)
print(indice_mas_cercano)
print(valor_mas_cercano)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
71
71


## 30 - ¿Cómo convertir una matriz `float` (32 bits) en tipo `int` (32 bits)?

`pista: view and [:] =`

In [64]:
matriz_float = np.array([[1.5, 2.7, 3.3],
                         [4.2, 5.1, 6.9]], dtype=np.float32)

matriz_int = matriz_float.astype(np.int32)
print(matriz_float)
print(matriz_int)

[[1.5 2.7 3.3]
 [4.2 5.1 6.9]]
[[1 2 3]
 [4 5 6]]


## 31 - ¿Cuál es el equivalente de `enumerate` para matrices en `numpy`?

`pista: np.ndenumerate, np.ndindex`

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Utilizar np.ndenumerate() para iterar sobre la matriz
print("Usando np.ndenumerate:")
for indice, valor in np.ndenumerate(matriz):
    print("Índice:", indice, "Valor:", valor)

# Utilizar np.ndindex() para obtener los índices de la matriz y luego acceder a los valores
print("\nUsando np.ndindex:")
for indice in np.ndindex(matriz.shape):
    print("Índice:", indice, "Valor:", matriz[indice])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


## 32 - Restar la media de cada fila a una matriz.

`pista: mean(axis=, keepdims=)`


In [65]:
matriz = np.array([[1, 2, 3],
                    [4, 5, 6],  
                    [7, 8, 9]])

media_filas = np.mean(matriz, axis=1, keepdims=True)

matriz_resta_media = matriz - media_filas

print(matriz)
print(media_filas)
print(matriz_resta_media)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


## 33 - ¿Cómo ordenar una matriz por la enésima columna?

`pista: argsort`

In [66]:
mat = np.array([
    [1, 4, 2],
    [3, 1, 5],
    [2, 6, 3]
])

indices_ordenados = np.argsort(mat[:, 2])

mat_ordenada = mat[indices_ordenados]

print(mat_ordenada)

[[1 4 2]
 [2 6 3]
 [3 1 5]]


## 34 - ¿Cómo saber si una matriz 2D tiene columnas nulas?

`pista: any, ~`


In [71]:
matriz_ejemplo = np.array([
    [1, 0, 3],
    [0, 0, 0],
    [4, 0, 6]
])
columnas_no_nulas = np.any(~(matriz_ejemplo == 0), axis=0)
print(not np.all(columnas_no_nulas))

True


## 35 - Encuentre el valor más cercano de un valor dado en una matriz.

`pista: np.abs, argmin, flat`


In [75]:
matriz_ejemplo = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
valor_dado = 5.5

distancia_absoluta = np.abs(matriz_ejemplo - valor_dado)

indice_mas_cercano = np.argmin(distancia_absoluta)

valor_mas_cercano = matriz_ejemplo.flat[indice_mas_cercano]

print("El valor más cercano a", valor_dado, "en la matriz es:", valor_mas_cercano)
print(distancia_absoluta)
print(indice_mas_cercano)
print(valor_mas_cercano)

El valor más cercano a 5.5 en la matriz es: 5
[[4.5 3.5 2.5]
 [1.5 0.5 0.5]
 [1.5 2.5 3.5]]
4
5
